### ISSUE TITLE
Cannot register/login through dev:vendor

### ISSUE THREAD

**Issue by Imoj-NGX** [mercurjs/mercur#12]
When running dev:vendor, the page loads up but I am not able to register through /register (it gets stuck). I am however able to post a vendor role via api. After creating vendor and approving, I still cannot log in using dev:vendor page for the newly created vendors. I however can log in as both admin or vendor via admin page. 
<img width="1303" alt="Screenshot 2024-06-11 at 7 52 01 PM" src="https://github.com/mercurjs/mercur/assets/112061627/2f26d3e9-9e47-4246-a2e1-99e74585374f">

**Comment by Imoj-NGX** [comment]
Never-mind, must run both admin and vendor simultaneously and don't forget to set your admin cors in env to 7002.

**Comment by bscw21027** [comment]
Hi Imoj-NGX,

I'm running through the exact same issue, and can't register or login on the vendor panel after running `yarn dev:vendor`.

I'm running both admin and vendor simultaneously.

This is my `.env` file.

```
JWT_SECRET=something
COOKIE_SECRET=something

DATABASE_TYPE="postgres"
REDIS_URL='redis://localhost:6379'
STORE_CORS='http://localhost:3000,http://localhost:7001'
ADMIN_CORS='http://localhost:7001,http://localhost:7002'
MEDUSA_FF_SALES_CHANNELS='false'
``` 
removed database url for obvious reasons. Can you help me to navigate this.
