### ISSUE TITLE
/admin/users/password-token not working

### ISSUE THREAD

**Issue by sonntag-philipp** [mercurjs/mercur#13]
The specified route is not working and returns 401 by default. I cannot get any breakpoint to intercept this response after some hours of debugging. So this is all information I can give you.

**Comment by sonntag-philipp** [comment]
See https://github.com/medusajs/medusa/issues/7804

**Comment by tomaszburas** [comment]
solution -> https://github.com/mercurjs/mercur-api-starter/pull/19
