### ISSUE TITLE
Seed error

### ISSUE THREAD

**Issue by Prat1143** [mercurjs/mercur#14]
I am trying to create a multi-vendor ecommerce website using medusa js.

Followed all the steps mentioned in - https://github.com/mercurjs/mercur. Then on running the cmd - yarn seed getting the error- 

[@mercurjs/vendor-ui] Could not find the admin UI build files. Please run "medusa-admin build" or enable "autoRebuild" in the plugin options to build the admin UI.
[@mercurjs/vendor-ui] Exiting process

My medusa-config.js code - 

`
const dotenv = require('dotenv');

let ENV_FILE_NAME = '';
switch (process.env.NODE_ENV) {
	case 'production':
		ENV_FILE_NAME = '.env.production';
		break;
	case 'staging':
		ENV_FILE_NAME = '.env.staging';
		break;
	case 'test':
		ENV_FILE_NAME = '.env.test';
		break;
	case 'development':
	default:
		ENV_FILE_NAME = '.env';
		break;
}

try {
	dotenv.config({ path: process.cwd() + '/' + ENV_FILE_NAME });
} catch (e) {}

// CORS when consuming Medusa from admin
const ADMIN_CORS = process.env.ADMIN_CORS || 'http://localhost:7000,http://localhost:7001';

// CORS to avoid issues when consuming Medusa from a client
const STORE_CORS = process.env.STORE_CORS || 'http://localhost:8000';

const DATABASE_URL = process.env.DATABASE_URL || 'postgres://localhost/medusa-starter-default';

const REDIS_URL = process.env.REDIS_URL || 'redis://localhost:6379';

const plugins = [
	`medusa-fulfillment-manual`,
	`medusa-payment-manual`,
	{
		resolve: `@medusajs/file-local`,
		options: {
			upload_dir: 'uploads',
		},
	},
	{
		resolve: '@rigby-software-house/mercurjs-vendor',
		options: {},
	},
	{
		resolve: '@medusajs/admin',
		options: {},
	},
];

const modules = {
	/*eventBus: {
    resolve: "@medusajs/event-bus-redis",
    options: {
      redisUrl: REDIS_URL
    }
  },
  cacheService: {
    resolve: "@medusajs/cache-redis",
    options: {
      redisUrl: REDIS_URL
    }
  },*/
};

/** @type {import('@medusajs/medusa').ConfigModule["projectConfig"]} */
const projectConfig = {
	jwtSecret: process.env.JWT_SECRET,
	cookieSecret: process.env.COOKIE_SECRET,
	store_cors: STORE_CORS,
	database_url: DATABASE_URL,
	admin_cors: ADMIN_CORS,
	// Uncomment the following lines to enable REDIS
	// redis_url: REDIS_URL
};

/** @type {import('@medusajs/medusa').ConfigModule} */
module.exports = {
	projectConfig,
	plugins,
	modules,
};

`
When I remove the line - 
{
		resolve: '@rigby-software-house/mercurjs-vendor',
		options: {},
},

the yarn seed cmd works fine. 

What am I missing here?

**Comment by vholik** [comment]
Try to comment out ui plugins `@medusajs/admin` and `@rigby-software-house/mercurjs-vendor` from plugins array in `medusa-config.js`.

Here is youtube [video link](https://www.youtube.com/watch?v=P_1AlB_-Esg&t=13s) with step by step guide in case you haven't seen it yet (1.20s timestamp)
