### ISSUE TITLE
Plugin with enableUI true not showing up in Vendor panel

### ISSUE THREAD

**Issue by NicolasGorga** [mercurjs/mercur#16]
Hello,

After installing https://github.com/vholik/medusa-custom-attributes in my backend, checking that it has the enableUI option set to true and starting the Vendor server, i don't see the plugin UI customizations, like the CustomAttributes page or Widget in product detail.

I have debugged the compiled js code and see that it effectively picks up the plugin in the utils _getPluginPaths_ function. Is it possible / tested the inclusion of plugins with UI customizations for VendorUI plugin?

**Comment by vholik** [comment]
The `medusa-custom-attributes` plugin is not supported in Mercur simply because it is a store plugin, not a marketplace plugin.
