### ISSUE TITLE
Can't register/login as vendor

### ISSUE THREAD

**Issue by bscw21027** [mercurjs/mercur#25]
Hi, 

I'm following the tutorial from youtube and ran `yarn dev:vendor` to open the vedor panel. Tried to register but it gets stuck and doesn't show the confirmation toast.

![image](https://github.com/user-attachments/assets/42b5a7dd-d010-48d4-b378-22bb7db75cac)

I'm running both admin and vendor simultaneously.

This is my .env file.

```
JWT_SECRET=something
COOKIE_SECRET=something

DATABASE_TYPE="postgres"
REDIS_URL='redis://localhost:6379'
STORE_CORS='http://localhost:3000,http://localhost:7001'
ADMIN_CORS='http://localhost:7001,http://localhost:7002'
DATABASE_URL='..'
MEDUSA_FF_SALES_CHANNELS='false'
```

**Comment by Reuben09** [comment]
Please, I’m having this same issue, I also tried to register using postman and it says 404 meaning route not found, can anybody help with this please

**Comment by Yprapashtica** [comment]
Having the same issue here, can't add a new user from Postman, get a 404 error saying "Cannot POST /vendor/users" in the URL `http://localhost:9000/vendor/users`

**Comment by githmin** [comment]
Experiencing the same issue

**Comment by turistua** [comment]
I was able to resolve the cors issues by removing .env.local file, changing middlewares.ts:16 to `middlewares: [cors(adminCors)],` and putting `ADMIN_CORS="http://localhost:7001,http://localhost:7002"` at .env file

**Comment by chrislicodes** [comment]
Thank you @turistua, that worked.

**Comment by sarrrimm** [comment]
> I was able to resolve the cors issues by removing .env.local file, changing middlewares.ts:16 to `middlewares: [cors(adminCors)],` and putting `ADMIN_CORS="http://localhost:7001,http://localhost:7002"` at .env file

it worked, thanks!. But now while trying to change the vendor account status from pending to active, it says an error occurred while updating the user status. and on the console it says "property status should not exist"
