### ISSUE TITLE
Medusa V2

### ISSUE THREAD

**Issue by Matb85** [mercurjs/mercur#31]
Hi,
is there any info on how to adjust the starter for Medusa V2?

**Comment by nzahariev** [comment]
I'm also interested in this topic. Please let me know if there is an update.

**Comment by farhan1199** [comment]
Any update on this?

**Comment by Lukem121** [comment]
bump

**Comment by gtomaka** [comment]
Thanks for asking! We are working on it. For now, you can find it under the v2 branch. By the end of the week, it should be fully completed and switched to the main branch.

**Comment by gtomaka** [comment]
v2 branch
