### ISSUE TITLE
mercur-api@workspace:. doesn't provide package requested by package

### ISSUE THREAD

**Issue by WissemBoujlida** [mercurjs/mercur#32]
I followed the following installation process:

node version: v22.11.0, (also I have tested v20.9.0, v23.2.0)
npm version: 10.9.0
yarn version: 4.2.2

```
npx mercurjs marketplace
```

```
cd /api 
```

```
yarn install
```
had the following errors:
YN0002: │ mercur-api@workspace:. doesn't provide @medusajs/framework (p19b46), requested by @medusajs/cache-redis.
➤ YN0002: │ mercur-api@workspace:. doesn't provide @medusajs/framework (p384b2), requested by @medusajs/event-bus-local.
➤ YN0002: │ mercur-api@workspace:. doesn't provide @medusajs/framework (p74954), requested by @medusajs/cache-inmemory.
➤ YN0002: │ mercur-api@workspace:. doesn't provide @medusajs/framework (pa716f), requested by @medusajs/file-local.
➤ YN0002: │ mercur-api@workspace:. doesn't provide @medusajs/framework (paff6d), requested by @medusajs/event-bus-redis.
➤ YN0002: │ mercur-api@workspace:. doesn't provide awilix (p563f1), requested by @medusajs/cache-redis.
➤ YN0002: │ mercur-api@workspace:. doesn't provide awilix (p721b4), requested by @medusajs/event-bus-redis.
➤ YN0002: │ mercur-api@workspace:. doesn't provide react (p01c95), requested by @medusajs/icons.
➤ YN0002: │ mercur-api@workspace:. doesn't provide react (p0801f), requested by prism-react-renderer.
➤ YN0002: │ mercur-api@workspace:. doesn't provide react (pdc37d), requested by @medusajs/ui.
➤ YN0002: │ mercur-api@workspace:. doesn't provide react (pe01b7), requested by @tanstack/react-query.
➤ YN0002: │ mercur-api@workspace:. doesn't provide react-dom (p532bc), requested by @medusajs/ui.
➤ YN0002: │ mercur-api@workspace:. doesn't provide webpack (p55215), requested by ts-loader.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.

```
yarn build
```

```
npx @medusajs/medusa-cli migrations run
```
had the following errors:

error:   Could not resolve required module: EventBusModuleService. Error: Make sure you have installed the default package: @medusajs/event-bus-local

error:   Could not resolve required module: CacheService. Error: Make sure you have installed the default package: @medusajs/cache-inmemory

Error: Make sure you have installed the default package: @medusajs/event-bus-local at loadInternalModule

**Comment by adaltonreis** [comment]
UP

**Comment by erdeneulzii** [comment]
Having the same issue :((

**Comment by kaushal-enstead** [comment]
1. fix this versions in package.json
```
"@medusajs/admin": "7.1.12",
"@medusajs/cache-inmemory": "1.8.11",
"@medusajs/cache-redis": "1.9.0",
"@medusajs/event-bus-local": "1.9.8",
"@medusajs/event-bus-redis": "1.8.13",
"@medusajs/file-local": "1.0.2",
"@medusajs/icons": "^1.2.1",
"@medusajs/medusa": "^1.20.6",
"@medusajs/ui": "^3.0.0",
"@rigby-software-house/mercurjs-vendor": "^0.0.4",
```

2.  fix at line 16 in middlewares.ts
```
middlewares: [cors(adminCors)],
```

3. src/api/index.ts -> add below code in last line of the file
```
registerOverriddenValidators(AdminUpdateUserRequest);
```

**Comment by vholik** [comment]
This error occurs because the latest package versions are specified in the `package.json`. Update the package versions in `package.json` to compatible Medusa 1.x versions to resolve the issue.

```json
"@medusajs/admin": "latest",
"@medusajs/cache-inmemory": "latest",
"@medusajs/cache-redis": "latest",
"@medusajs/event-bus-local": "latest",
"@medusajs/event-bus-redis": "latest",
"@medusajs/file-local": "latest", 

// dev dependencies
"@medusajs/medusa-cli": "latest",
```
