### ISSUE TITLE
i can`t create categories from admin.

### ISSUE THREAD

**Issue by JuanEliasJabib02** [mercurjs/mercur#4]
![image](https://github.com/mercurjs/mercur/assets/95072028/5f7997de-088e-447a-8469-02d57fc4c906)
 im getting this error when i try to create a category, what can be?

**Comment by cwierzbicki00** [comment]
I believe it is because admin doesn't have a storefront associated with it, which leads to this error.

**Comment by samirjabib** [comment]
need active the feature is on beta.

file---> medusa-config.js

![image](https://github.com/mercurjs/mercur/assets/98964077/293c03f3-bfb1-4878-90af-d55dd8763fc6)
