### ISSUE TITLE
Dont show users of admins and other vendors

### ISSUE THREAD

**Issue by HadiSDev** [mercurjs/mercur#6]
In the Vendor Admin Panel under users we don't want to show any other user other than the vendor team:
![image](https://github.com/mercurjs/mercur/assets/10367624/af3fab15-bd21-40c7-a1f8-54477dc57d6b)

**Comment by HadiSDev** [comment]
I also realized that the role is wrong. It is set to Admin. Big security risk

**Comment by vholik** [comment]
Role admin only applies to the store it does not applies for the whole marketplace. There is `is_admin` column in users table that differentiates admins from vendors.
