### ISSUE TITLE
Cannot login to Admin first time

### ISSUE THREAD

**Issue by altermod** [mercurjs/mercur#8]
During initial setup I tried logging into the admin panel following the instructions on npm
https://www.npmjs.com/package/mercurjs

admin@medusa-test.com
password supersecret

![image](https://github.com/mercurjs/mercur/assets/101657684/c7c9dd35-c7a8-4435-ab0e-5ee9ab8cff2d)

Can you provide the password or workaround for this? Thanks

**Comment by altermod** [comment]
Well I see the admin backend is throwing this error: 
error:   User with email: admin@medusa-test.com was not found

But I can see the user in the user table exists.
![image](https://github.com/mercurjs/mercur/assets/101657684/5a2f70b3-585e-4625-8efb-750c117864ce)

**Comment by altermod** [comment]
Was I supposed to put the REVALIDATE_SECRET=supersecret in the admin or api .env file
![image](https://github.com/mercurjs/mercur/assets/101657684/575ccf54-5999-427c-8076-0af48dbb4241)

**Comment by arpitXCRM** [comment]
Hi altermod what is the resolution to this issue i am getting the same error. @altermod
