### ISSUE TITLE
installation issues on mac localhost, storefront works, admin and vendor cannot login 401 unauthorized Please Help 🙏 

### ISSUE THREAD

**Issue by altermod** [mercurjs/mercur#9]
I was able to get all four servers up and running. The front-end store connectivity to the api works fine. But the Admin and Vendors are having 401 errors on the backend. I followed all the instructions

Here is the output on the api for a login request from the admin login
![image](https://github.com/mercurjs/mercur/assets/101657684/5a342636-872b-425e-a84a-3aae6a897a7e)

I would appreciate any help on figuring out why I cannot authenticate with admin and vendor front-ends to the api.

The admin and vendor .env files are like so
![image](https://github.com/mercurjs/mercur/assets/101657684/4343be03-856d-4162-a46d-eb71ada07b65)

The api .env file is like so
![image](https://github.com/mercurjs/mercur/assets/101657684/8b867f8e-cb3f-4334-a460-f1ee47b3ffe5)

Like I said I seeded the database and the store front-end works. I was able to create a customer as well.
![image](https://github.com/mercurjs/mercur/assets/101657684/d4031583-3057-44c0-9ae0-64d3cc801e28)

There was one particular tweak I had to make to the api folder api/.eslintrc.js file tho, for the parseOptions I had to change project from 'tsconfig.json' to 'api/tsconfig.json'
![image](https://github.com/mercurjs/mercur/assets/101657684/c5430747-8899-47ae-80d7-0311c7fb6d26)

That was because there were some path errors for users.ts if I didn't add the api to the path.
![image](https://github.com/mercurjs/mercur/assets/101657684/646d0b51-394b-4eeb-8bbd-24ee08ae8e81)

**Comment by arpitXCRM** [comment]
When I try to login with the default given for admin it says unauthorized.
